# Generated by Django 5.0.4 on 2024-05-26 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_poll_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 19, 3, 55, 457335), verbose_name='date published'),
        ),
    ]
