# Generated by Django 5.0.4 on 2024-05-26 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_poll_poll_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 20, 25, 19, 149833), verbose_name='poll end'),
        ),
    ]
