# Generated by Django 5.0.4 on 2024-05-28 07:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_alter_poll_poll_end'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 14, 22, 53, 684770), verbose_name='poll end'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poll.option')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poll.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
