# Generated by Django 5.0.4 on 2024-05-28 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_alter_poll_poll_end_alter_vote_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='voted_on',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date voted'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 14, 27, 13, 872615), verbose_name='poll end'),
        ),
    ]
